### PR TITLE
Updated ruby-tunnel README

### PR DESCRIPTION
**Pull request by gabrieljackson**
Information has been added on how to create and modify this app.

Please review @mbhinder @zquestz

### CODE REVIEW

**Comment by mbhinder** [comment]
LGTM, nit: I think we should we rename the glue_URI to GLUE_URI to be more consistent with shell naming conventions.

**Comment by mbhinder** [comment]
I grepped for that envvar and nothing seems to be using that in system tests in continuum

**Comment by gabrieljackson** [comment]
Agreed! Updated.

**Comment by mbhinder** [comment]
LGTM

**Comment by zquestz** [comment]
LGTM!

**Pull request merged**
