### PR TITLE
Added Slogger tool

### PR DESCRIPTION
**Pull request by gabrieljackson**
Slogger is a simple syslog server that is built via the bash staging
process.

Slogger listens on port `1999` by default. All log messages that hit
this port will be appended to the `/app/logs/all-remote-logs` file.
Due to the startup process ending with tailing this file, all log
messages can be viewed in realtime by running `apc job logs slogger`.

By adding a TCP route to the Slogger job and then adding an app drain
to other apps, this allows the collection of job logs via Slogger.

### CODE REVIEW

**Comment by gabrieljackson** [comment]
Please review @klobucar @zquestz @emil2k

Example output generated by a Go app on the cluster:

```
gabe-mbp:~/gabecode/samples/bash/slogger$ curl go1.gabe.sandbox.demo.apcera.net
{
  "API_Instance": "86aba801-7797-462e-939f-98bbf546a09e",
  "API_FQN": "job::/sandbox/gabe::go1",
  "Number": 81
}
```

Logs as seen by running `apc job logs slogger`:

```
[stdout] ###############################################################
[stdout] ##                   SLOGGER VERSION: 0.1                    ##
[stdout] ###############################################################
[stdout] ##                   START SYSLOG SERVICE                    ##
[stdout] ###############################################################
[stdout]  * Starting system logging syslog-ng
[stdout]    ...done.
[stdout] syslog-ng 3.6.4
[stdout] Installer-Version: 3.6.4
[stdout] Revision: 
[stdout] Compile-Date: Jul 30 2015 17:30:46
[stdout] Available-Modules: dbparser,afsocket-tls,confgen,pseudofile,sdjournal,afstomp,basicfuncs,cryptofuncs,afprog,affile,afuser,syslogformat,afsocket-notls,graphite,afmongodb,afsocket,afamqp,system-source,linux-kmsg-format,csvparser
[stdout] Enable-Debug: off
[stdout] Enable-GProf: off
[stdout] Enable-Memtrace: off
[stdout] Enable-IPv6: on
[stdout] Enable-Spoof-Source: off
[stdout] Enable-TCP-Wrapper: off
[stdout] Enable-Linux-Caps: off
[stdout] ###############################################################
[stdout] ##     RUN NETSTAT TO ENSURE SYSLOG IS LISTENING ON 1999     ##
[stdout] ###############################################################
[stdout] Active Internet connections (only servers)
[stdout] Proto Recv-Q Send-Q Local Address           Foreign Address         State      
[stdout] tcp        0      0 *:1999                  *:*                     LISTEN     
[stdout] Active UNIX domain sockets (only servers)
[stdout] Proto RefCnt Flags       Type       State         I-Node   Path
[stdout] unix  2      [ ACC ]     STREAM     LISTENING     27146169 /app/syslog-ng/var/syslog-ng.ctl
[stdout] unix  2      [ ACC ]     STREAM     LISTENING     27144969 /var/lib/continuum/instances/1c109868/socket
[stdout] ###############################################################
[stdout] ##                 BEGINNING OF REMOTE LOGS                  ##
[stdout] ###############################################################
[stdout] Jul 30 17:35:30 10.0.0.75 job.09e0b44e-9f9f-4362-83b9-d88bd57ba360.stdout[2981]: {
[stdout] Jul 30 17:35:30 10.0.0.75 job.09e0b44e-9f9f-4362-83b9-d88bd57ba360.stdout[2981]:   "API_Instance": "86aba801-7797-462e-939f-98bbf546a09e",
[stdout] Jul 30 17:35:30 10.0.0.75 job.09e0b44e-9f9f-4362-83b9-d88bd57ba360.stdout[2981]:   "API_FQN": "job::/sandbox/gabe::go1",
[stdout] Jul 30 17:35:30 10.0.0.75 job.09e0b44e-9f9f-4362-83b9-d88bd57ba360.stdout[2981]:   "Number": 81
[stdout] Jul 30 17:35:30 10.0.0.75 job.09e0b44e-9f9f-4362-83b9-d88bd57ba360.stdout[2981]: }
```

**Comment by mbhinder** [comment]
LGTM

**Comment by gabrieljackson** [comment]
@alextoombs, this is the syslog job I was referring to.

**Comment by alextoombs** [comment]
:+1: (but I'm bash-stupid, so trust Preet's opinion over mine)

**Pull request merged**
