### PR TITLE
Remove demo-node-todo app

### PR DESCRIPTION
**Pull request by gabrieljackson**
The functionality of this app is available in demo-node-todo-v2.

I can't seem to find a reason to keep this around when https://github.com/apcera/continuum-sample-apps/tree/master/demo-node-todo-v2 is available. Thoughts?

@zquestz @mbhinder

### CODE REVIEW

**Comment by zquestz** [comment]
We use this extensively in system tests...

**Comment by mbhinder** [comment]
Can we just rename v2 to demo-node-todo?

**Comment by tstatler** [comment]
Can engineering use samples from the private "sample-apps" repo, and let the (public) "continuum-sample-apps" repo be only for customer-facing samples? Or maybe you already do...

**Comment by krobertson** [comment]
@tstatler I don't believe that is a safe assumption, since @rswelch has a ticket filed to have system tests move over to use the public repo, rather than having two repos.

**Comment by gabrieljackson** [comment]
Yeah, I do know that we are attempting to consolidate the repos in order to reduce redundancy.

Another option, I suppose, is merging the v2 changes into this app and then examine system testing for any new failures.

If any of this is too risky to be done currently, then I will close the PR. I was just attempting to do a round of updates and improvements on this repo.

**Comment by sdemura** [comment]
SC's rely heavily on the todo apps. Let's make sure to keep them in the loop on any changes.

**Comment by gabrieljackson** [comment]
It looks like it may just be best to leave this app be for the moment. Any final thoughts?

If not, I will close the PR.

**Comment by zquestz** [comment]
Keep for now.

**Pull request closed without merging**
